# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# 			DO NOT TOUCH ANYTHING BELOW THIS LINE			        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

version: '3.7'
services:
      
  kafka-server:
    image: nexus.devtools.proyecto-sol.es:9085/apache/kafka:3.7.0
    ports:
      - "31111:31111"
      - "9092:31111"
    networks:
      - orangebank
    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-server:9093

      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_ADVERTISED_LISTENERS: BROKER://:9092,CLIENT://localhost:31111
      KAFKA_LISTENERS: BROKER://:9092,CLIENT://:31111,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      
networks:
  orangebank:
    name: orangebank
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  hadoop-binaries:
  hadoop-namenode:
  hadoop-datanode:

